MODEL:
  BERT_CKPT: "/data/chendian/pretrained_bert_models/chinese-macbert-base/"  # "bert-base-chinese"
  DEVICE: "cuda"
  NAME: "cdmac"
  # switches
  ENCODER_TYPE: 'pinyin_merged'
  MERGE_MASK_TYPE: 'gold'  # try again
  MASK_CONFUSIONS: True  
  PREDICT_PINYINS: True
  PREDICT_FAULTY_POSITIONS: True
  # settings
  HYPER_PARAMS: [ .5 ]  # w * cor + (1-w) * det  # [loss_coefficient]
  GPU_IDS: [ 0 ]
  WEIGHTS: "both_gold_ep09.dcn.ckpt"

DATASETS:
  # TRAIN: "/data/chendian/bbcm_datasets/csc_aug/sighan15_train_z4.220308.json"
  # TRAIN: "/home/chendian/BBCM/datasets/csc_aug/sighan15_test.ct_covered.w.json"
  # VALID: "/home/chendian/BBCM/datasets/csc_aug/sighan15_test.ct_covered.w.json"
  # TEST: "/home/chendian/BBCM/datasets/csc_aug/sighan15_test.ct_covered.w.json"
  # TEST: "/data/chendian/bbcm_datasets/csc_aug/sighan15_train_z4.220308.json"
  # TRAIN: "/home/chendian/BBCM/datasets/csc/train.json"
  # VALID: "/home/chendian/BBCM/datasets/csc/dev.json"
  TEST: "/home/chendian/BBCM/datasets/csc/test.json"

SOLVER:
  BASE_LR: 1e-4
  WEIGHT_DECAY: 5e-8
  BATCH_SIZE: 4
  MAX_EPOCHS: 10
  ACCUMULATE_GRAD_BATCHES: 1

DATALOADER:
  NUM_WORKERS: 8

TEST:
  BATCH_SIZE: 16

TASK:
  NAME: "csc"

MODE: ['test']
OUTPUT_DIR: "checkpoints/cdmac_dcn_pymerged_goldmask_220406/"
