MODEL:
  BERT_CKPT: "/data/chendian/pretrained_bert_models/chinese_L-12_H-768_A-12/"  # "bert-base-chinese"
  DEVICE: "cuda"
  NAME: "cdsmb"
  # [loss_coefficient]
  HYPER_PARAMS: [ 0.5 ]
  GPU_IDS: [ 0 ]
  WEIGHTS: "epoch=01_valid_cor_loss=0.0270.ckpt"

DATASETS:
  TRAIN: "/home/chendian/BBCM/datasets/csc/train.json"
  VALID: "/home/chendian/BBCM/datasets/csc/dev.json"
  TEST: "/home/chendian/BBCM/datasets/csc/test.json"

SOLVER:
  BASE_LR: 1e-4
  WEIGHT_DECAY: 5e-8
  BATCH_SIZE: 4
  MAX_EPOCHS: 5
  ACCUMULATE_GRAD_BATCHES: 4

DATALOADER:
  NUM_WORKERS: 16

TEST:
  BATCH_SIZE: 16

TASK:
  NAME: "csc"

MODE: ["test"]
OUTPUT_DIR: "checkpoints/cdsmb_bbcm_220304_bothsim"
