MODEL:
  BERT_CKPT: "bert-base-chinese"
  DEVICE: "cuda"
  NAME: "cdsmb"
  # [loss_coefficient]
  HYPER_PARAMS: [ 0.5 ]
  GPU_IDS: [ 0,1,2,3 ]

DATASETS:
  TRAIN: "datasets/csc/train.json"
  VALID: "datasets/csc/dev.json"
  TEST: "datasets/csc/test.json"

SOLVER:
  BASE_LR: 1e-4
  WEIGHT_DECAY: 5e-8
  BATCH_SIZE: 4
  MAX_EPOCHS: 10
  ACCUMULATE_GRAD_BATCHES: 4

DATALOADER:
  NUM_WORKERS: 8

TEST:
  BATCH_SIZE: 16

TASK:
  NAME: "csc"

OUTPUT_DIR: "checkpoints/cdsmb_1xsim0.05_0120"
