MODEL:
  BERT_CKPT: "hfl/chinese-macbert-base"
  DEVICE: "cuda"
  NAME: "macbert4csc"
  # [loss_coefficient]
  HYPER_PARAMS: [ 0.5 ]
  GPU_IDS: [ 0 ]
#  WEIGHTS: "epoch=6-val_loss=0.07.ckpt"

DATASETS:
  TRAIN: "datasets/csc/train.json"
  VALID: "datasets/csc/dev.json"
  TEST: "datasets/csc/test.json"

SOLVER:
  BASE_LR: 1e-4
  WEIGHT_DECAY: 5e-8
  BATCH_SIZE: 8
  MAX_EPOCHS: 10
  ACCUMULATE_GRAD_BATCHES: 4

DATALOADER:
  NUM_WORKERS: 8

TEST:
  BATCH_SIZE: 8

TASK:
  NAME: "csc"

OUTPUT_DIR: "checkpoints/macbert4csc_dynamic_1027"
